security:
    encoders:
        Marcoshoya\MarquejogoBundle\Entity\AdmUser:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        admin:
            entity: { class: MarcoshoyaMarquejogoBundle:AdmUser, property: username }
        provider:
            entity: { class: MarcoshoyaMarquejogoBundle:Provider, property: email }
        customer:
            entity: { class: MarcoshoyaMarquejogoBundle:Customer, property: email }

    firewalls:
        site:
            context: website
            pattern: ^/(?!(fornecedor|cliente|adm)).*$
            anonymous: true
            
        admin:
            anonymous: ~
            pattern:    ^/adm/.*
            form_login:
                provider: admin
                check_path: /adm/login_check
                login_path: /adm/login
                default_target_path: /adm

        customer:
            anonymous: ~
            context: website
            pattern:    ^/cliente/.*
            form_login:
                provider: customer
                check_path: /cliente/login_check
                login_path: /cliente/login
                default_target_path: /cliente
                
        provider:
            anonymous: ~
            pattern:    ^/fornecedor/.*
            form_login:
                provider: provider
                check_path: /fornecedor/login_check
                login_path: /fornecedor/login
                default_target_path: /fornecedor

    access_control:
        - { path: ^/adm/doLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adm/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adm, roles: ROLE_ADMIN }
        - { path: ^/cliente/cadastrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cliente/doRegister, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cliente/doLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cliente/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cliente, roles: [ROLE_ADMIN, ROLE_CUSTOMER] }
        - { path: ^/fornecedor/doLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fornecedor/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fornecedor, roles: [ROLE_ADMIN, ROLE_PROVIDER] }
