#security:
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~

security:
    encoders:
        Marcoshoya\MarquejogoBundle\Entity\AdmUser:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        admin:
            entity: { class: MarcoshoyaMarquejogoBundle:AdmUser, property: username }

    firewalls:
        admin:
            anonymous: ~
            pattern:    ^/adm
            form_login:
                check_path: /adm/login_check
                login_path: /adm/login
                default_target_path: /adm
                
        customer:
            anonymous: ~
            pattern:    ^/cliente
            form_login:
                check_path: /cliente/login_check
                login_path: /cliente/login
                default_target_path: /cliente

    access_control:
        - { path: ^/adm/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adm, roles: ROLE_ADMIN }
        - { path: ^/cliente/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cliente, roles: [ROLE_ADMIN, ROLE_CUSTOMER] }
        