marquejogo_homepage:
    path:     /
    defaults: { _controller: MarcoshoyaMarquejogoBundle:Site/Main:index }
    
marquejogo_adm:
    resource: "@MarcoshoyaMarquejogoBundle/Controller/Adm/"
    type:      annotation
    prefix:    /adm

marquejogo_site:
    resource: "@MarcoshoyaMarquejogoBundle/Controller/Site/"
    type:      annotation