marquejogo_homepage:
    path:     /
    defaults: { _controller: MarcoshoyaMarquejogoBundle:Default:index }
    
marquejogo_adm:
    resource: "@MarcoshoyaMarquejogoBundle/Controller/Adm/"
    type:      annotation
    prefix:    /adm
