services:
    marcoshoya_marquejogo.type.entity_hidden:
        class: Marcoshoya\MarquejogoBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: entity_hidden }

    marcoshoya_marquejogo.service.base:
        abstract:  true
        class: Marcoshoya\MarquejogoBundle\Service\BaseService
        arguments: ["@doctrine.orm.entity_manager", "@logger"]

    marcoshoya_marquejogo.service.personservice:
        class: Marcoshoya\MarquejogoBundle\Service\PersonService
        parent: marcoshoya_marquejogo.service.base
        properties:
             autocomplete: "@marcoshoya_marquejogo.service.autocomplete"

    marcoshoya_marquejogo.service.autocomplete:
        class: Marcoshoya\MarquejogoBundle\Service\AutocompleteService
        parent: marcoshoya_marquejogo.service.base

    marcoshoya_marquejogo.service.search:
        class: Marcoshoya\MarquejogoBundle\Service\SearchService
        parent: marcoshoya_marquejogo.service.base

    marcoshoya_marquejogo.service.product:
        class: Marcoshoya\MarquejogoBundle\Service\ProductService
        parent: marcoshoya_marquejogo.service.base
