services:
    marcoshoya_marquejogo.type.entity_hidden:
        class: Marcoshoya\MarquejogoBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: entity_hidden }

    marcoshoya_marquejogo.service.personservice:
        class: Marcoshoya\MarquejogoBundle\Component\Person\PersonService
        arguments: ["@doctrine.orm.entity_manager"]